controller:
  kind: DaemonSet

  reportNodeInternalIp: true

  hostPort:
    enabled: true
    ports:
      http: 80
#      https: 443

  service:
    type: NodePort
  ingressClassResource:
    name: nginx-internal  # ‚Üê Use a unique name
    enabled: true
    default: false